/*
  Put future DAILY WORDS here. Everyone sees the same word because the app
  selects from this list using the calendar date. Keep entries five letters.
  Add as many as you like; when the list ends it wraps around.
*/
window.FAMILY_WORDS = [
  "CRANE","BRAVE","PLANT","SHORE","MUSIC","CLOUD","GRAPE","STONE","LIGHT","HOUSE",
  "BREAD","TRACK","SMILE","RIVER","CHAIR","FIELD","NIGHT","APPLE","BEACH","WORLD",
  "DRIVE","CLEAN","GREEN","TRAIN","SWEET","FLAME","BRICK","WATER","GLASS","QUIET",
  "EARTH","PILOT","DREAM","CROWN","SHEEP","MOUSE","ROUND","SPICE","HEART","BLEND",
  "POINT","LAUGH","FRESH","BLACK","WHITE","BROWN","STORM","PRIDE","SPACE","MAPLE",
  "HONEY","PEACH","LEMON","MANGO","ROAST","CREAM","SAUCE","PASTA","TOAST","BACON",
  "HOPPY","MALTS","YEAST","CASKS","KEGGS","BREWS","PUBBY","PINTS","GRAIN","AMBER",
  "CLIMB","ROUTE","TRAIL","RIDGE","ROCKS","CAMPS","WOODS","LAKES","SLOPE","BOOTS"
];

/* Additional accepted guesses. Daily words are always accepted too. */
window.EXTRA_GUESSES = [
  "ABOUT","ABOVE","ACTOR","ACUTE","ADORE","AFTER","AGAIN","AGILE","ALERT","ALIEN",
  "ALIVE","ALONE","ANGLE","APART","ARGUE","ARISE","ARROW","ASIDE","AUDIO","AVOID",
  "AWARE","BADGE","BASIC","BATCH","BEGIN","BELOW","BENCH","BERRY","BIRTH","BLOCK",
  "BOARD","BRAIN","BRAND","BREAK","BRING","BROAD","BUILD","BURST","CARRY","CATCH",
  "CAUSE","CHAIN","CHARM","CHART","CHASE","CHEST","CHILD","CHOIR","CLAIM","CLASS",
  "CLEAR","CLOCK","CLOSE","COAST","COLOR","COULD","COUNT","COURT","COVER","CRASH",
  "CRISP","CROSS","CYCLE","DANCE","DEALT","DEATH","DEPTH","DOUBT","DOZEN","DRAFT",
  "DRINK","EAGER","EARLY","EMPTY","ENJOY","ENTER","ENTRY","EQUAL","ERROR","EVENT",
  "EXACT","EXTRA","FAITH","FALSE","FAULT","FIGHT","FINAL","FIRST","FLOOR","FOCUS",
  "FORCE","FRAME","FRONT","FRUIT","GIANT","GIVEN","GLOBE","GOING","GRAND","GRASS",
  "GREAT","GROUP","GUARD","GUESS","HAPPY","HEAVY","HORSE","HOTEL","IDEAL","IMAGE",
  "JOINT","JUDGE","KNIFE","LARGE","LATER","LEARN","LEAST","LEAVE","LEVEL","LOCAL",
  "LUCKY","LUNCH","MAJOR","MAKER","MATCH","METAL","MIGHT","MONEY","MONTH","MOTOR",
  "MOUNT","MOVIE","NEVER","NORTH","NOVEL","OCEAN","OFFER","OFTEN","ORDER","OTHER",
  "PAINT","PANEL","PARTY","PEACE","PHONE","PLACE","PLAIN","PLATE","POWER","PRESS",
  "PRICE","PRIME","PROUD","QUEEN","QUICK","RADIO","RAISE","REACH","READY","RIGHT",
  "ROUGH","ROYAL","SCALE","SCORE","SERVE","SHAPE","SHARE","SHARP","SHEET","SHIFT",
  "SHORT","SIGHT","SKILL","SLEEP","SMALL","SMART","SOLID","SOUND","SOUTH","SPEED",
  "SPORT","STAGE","STAND","START","STEAM","STEEL","STILL","STOCK","STORE","STUDY",
  "STYLE","SUGAR","TABLE","TASTE","TEACH","THANK","THEIR","THEME","THERE","THING",
  "THINK","THREE","THROW","TIGER","TODAY","TOTAL","TOUCH","TOWER","TREAT","TREND",
  "TRUCK","TRUST","UNDER","UNION","VALUE","VIDEO","VISIT","VOICE","WASTE","WATCH",
  "WHEEL","WHOLE","WOMAN","WRITE","YOUNG"
];
